#
# bundle exec jekyll serve --config "_config.yml,_config_dev.yml"  --incremental
#
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ideas
tagline:          'Cause a Scene'
description:      'A collection of ideas compiled by <a href="https://twitter.com/realdavidawad" target="_blank">@realdavidawad</a>.'
# url:              http://davidawad.com
# baseurl:          /
url: https://localhost
baseurl:          ''

# project-images: public/img/projects
# imageoptim:
  # svgo: false
  # verbose: false

# # css compression hopefully
# sass:
  # style: compressed

# assets:
  # digest: true
  # defaults:
    # js: {integrity: true} # true on JEKYLL_ENV=production
    # css: {integrity: true} # true on JEKYLL_ENV=production
    # img: {integrity: true} # true on JEKYLL_ENV=production

author:
  name:           'David Awad'
  url:            https://twitter.com/realdavidawad

paginate:         5

github:
  repo:           https://github.com/davidawad/blog

# Gems
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  # - jekyll-assets
  # - jekyll-offline
  # - jekyll-compress-images


links:
  email:     me@davidawad.com
  fb:        https://fb.com/david.a.awad
  twitter:   https://twitter.com/realdavidawad
  instagram:   https://instagram.com/realdavidawad
  spotify:   https://open.spotify.com/user/1253499829
  angellist: https://angel.co/davidawad
  github:    https://github.com/davidawad
  linkedin:  https://linkedin.com/in/davidawad64
  so:        https://stackoverflow.com/users/2178438/davidawad

# for jekyll-seo
twitter:
  username: realdavidawad

# TODO maybe breaking build for jekyll-offline
# offline:
  # strategy: cache-first-network-fallback

caching:
  path: ".jekyll-cache/assets"
  type: file # Possible values: memory, file
  enabled: true


social:
  name: David Awad
  links:
    - https://twitter.com/realdavidawad
    - https://www.facebook.com/david.a.awad
    - https://www.linkedin.com/in/davidawad64
    - https://plus.google.com/+davidawad64
    - https://github.com/davidawad
    - https://instagram.com/_davidawad
    - https://stackoverflow.com/users/2178438/davidawad

## jekyll archives configuration
jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tag

  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: tag-archive

  permalinks:
    year:  /:year/
    month: /:year/:month/
    day:   /:year/:month/:day/
    tag:   /tag/:name/

# KEYS
# bitcoin pubkey address
pubkey: 1gtRkH3399UipceRUG2xWRyYsYQk84SFM

# thankfully just comments gives no fucks
just_comments_key: dc79fd19-c673-45cc-a6ca-077cde204565

sources:
  - public/css


# jekyll compilation time speedup by ignoring files
exclude:
    - _site
    - _assets
    - bourbon
    - node_modules
    - bower_components

# don't blow away the git submodule
keep_files: [
  .git
]

# fix stupid local warning in dev
# github: [metadata]

